# Core DSL classes and dependencies will be loaded automatically at execution

### Dataset description ###
# Real data at the five energy points
# (sample-name convention: [BOSS version]_[CMS energy in MeV])
data_points = [
  DatasetManager.real_data.find("703_4230"),   # 4.230 GeV
  DatasetManager.real_data.find("703_4260"),   # 4.260 GeV (psi(4260) nominal point)
  DatasetManager.real_data.find("703_4360"),   # 4.360 GeV
  DatasetManager.real_data.find("703_4420"),   # 4.420 GeV
  DatasetManager.real_data.find("703_4600")    # 4.600 GeV
]

# Matching inclusive MC at each energy point (background / efficiency study)
incMC_points = [
  DatasetManager.inclusive_mc.find("703_4230"),
  DatasetManager.inclusive_mc.find("703_4260"),
  DatasetManager.inclusive_mc.find("703_4360"),
  DatasetManager.inclusive_mc.find("703_4420"),
  DatasetManager.inclusive_mc.find("703_4600")
]

### Decay cards (EvtGen format) ###
# Top mother psi(4260) (BESIII/KkMC convention); ISR is generated by KkMC at the
# top level and FSR by PHOTOS/VLL in the J/psi -> l+ l- decay.

# Mode 1: e+e- -> pi+ pi- X(3823), X(3823) -> gamma chi_c1, chi_c1 -> gamma J/psi, J/psi -> e+ e-
decay_card_chic1_ee = <<~DECAYCARD
    Decay psi(4260)
    1.0000 pi+ pi- X(3823)      PHSP;
    Enddecay

    Decay X(3823)
    1.0000 gamma chi_c1         PHSP;
    Enddecay

    Decay chi_c1
    1.0000 gamma J/psi          PHSP;
    Enddecay

    Decay J/psi
    1.0000 e+ e-                PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# Mode 2: same as mode 1 but J/psi -> mu+ mu-
decay_card_chic1_mumu = <<~DECAYCARD
    Decay psi(4260)
    1.0000 pi+ pi- X(3823)      PHSP;
    Enddecay

    Decay X(3823)
    1.0000 gamma chi_c1         PHSP;
    Enddecay

    Decay chi_c1
    1.0000 gamma J/psi          PHSP;
    Enddecay

    Decay J/psi
    1.0000 mu+ mu-              PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# Mode 3: X(3823) -> gamma chi_c2, chi_c2 -> gamma J/psi, J/psi -> e+ e-
decay_card_chic2_ee = <<~DECAYCARD
    Decay psi(4260)
    1.0000 pi+ pi- X(3823)      PHSP;
    Enddecay

    Decay X(3823)
    1.0000 gamma chi_c2         PHSP;
    Enddecay

    Decay chi_c2
    1.0000 gamma J/psi          PHSP;
    Enddecay

    Decay J/psi
    1.0000 e+ e-                PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# Mode 4: X(3823) -> gamma chi_c2, chi_c2 -> gamma J/psi, J/psi -> mu+ mu-
decay_card_chic2_mumu = <<~DECAYCARD
    Decay psi(4260)
    1.0000 pi+ pi- X(3823)      PHSP;
    Enddecay

    Decay X(3823)
    1.0000 gamma chi_c2         PHSP;
    Enddecay

    Decay chi_c2
    1.0000 gamma J/psi          PHSP;
    Enddecay

    Decay J/psi
    1.0000 mu+ mu-              PHOTOS VLL;
    Enddecay

    End
DECAYCARD

### Exclusive signal MC ###
# 40k events for each of the four modes at EVERY energy point.
# create_exclusive_mc_for returns one ExclusiveMC per dataset (auto-suffixed sample name).
exMC_chic1_ee = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "sig_chic1_ee"
  config.events        = 40_000
  config.decay_card    = decay_card_chic1_ee
  config.cross_section = :default
end

exMC_chic1_mumu = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "sig_chic1_mumu"
  config.events        = 40_000
  config.decay_card    = decay_card_chic1_mumu
  config.cross_section = :default
end

exMC_chic2_ee = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "sig_chic2_ee"
  config.events        = 40_000
  config.decay_card    = decay_card_chic2_ee
  config.cross_section = :default
end

exMC_chic2_mumu = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "sig_chic2_mumu"
  config.events        = 40_000
  config.decay_card    = decay_card_chic2_mumu
  config.cross_section = :default
end

# Save the MC configurations for reproducibility (save_to_config is per ExclusiveMC)
[exMC_chic1_ee, exMC_chic1_mumu, exMC_chic2_ee, exMC_chic2_mumu].flatten.each do |mc|
  mc.save_to_config(format: :yaml, file_path: 'temp_for_test')
end

### Event selection (BOSS) ###
# All four modes (gamma chi_c1 / gamma chi_c2, J/psi -> e+e- / mu+mu-) share the
# identical final state pi+ pi- gamma gamma l+ l- and the identical selection chain;
# they are separated later in ROOT by the M(gamma_H J/psi) window. A single Algorithm
# instance is therefore used for all of them.
alg_name = "PiPiGammaGammaLL"
my_algorithm = Algorithm.new(alg_name)
my_algorithm.set_header(["#{alg_name}Alg/#{alg_name}.h"])
            .set_constant({"ECMS" => [:double, 4.260]})   # nominal point; per-run beam energy used at execution for the scan
            .set_alias({"std::vector<double>" => "Vdouble"})

event_selection = Selection.new
event_selection.select_track {          # Charged track selection
                  cos_theta   0.93      # |cos(theta)| < 0.93
                  Vz          10.0      # |Vz| < 10 cm along the beam axis
                  Vr          1.0       # Vr < 1 cm in the transverse plane
                  nChrp       "==2"     # Exactly 2 positively charged tracks
                  nChrn       "==2"     # Exactly 2 negatively charged tracks
                  nNet        "==0"     # Net charge zero
                }
               .select_photon {         # Photon selection
                  tdc_emc_start      0       # TDC start time
                  tdc_emc_end        14      # TDC end time
                  angle_to_track     10.0    # At least 10 degrees from the nearest charged track
                  energyThreshold_b  0.025   # 25 MeV threshold in the EMC barrel
                  energyThreshold_e  0.050   # 50 MeV threshold in the EMC endcap
                  nGam               ">=2"   # At least two photon candidates
                }
               .pid(method: :probability) {   # Particle identification (probability method)
                  prob_cut   0.001            # PID probability > 0.001
                  identify_high_momentum_leptons treat_as_lepton_if_momentum_above: 1.0,
                                                 treat_as_electron_if_energy_above: 0.6  # p>1.0 GeV -> lepton; EMC eraw>0.6 GeV -> electron, else muon
                  identify :pion, against: [:kaon]   # pi+/pi- separation from kaons
                  npip   "==1"                # Exactly one pi+
                  npim   "==1"                # Exactly one pi-
                  nlp    "==1"                # Exactly one l+
                  nlm    "==1"                # Exactly one l-
                }
               .kinematic_fit([:pip, :pim, :gamma, :gamma, :lp, :lm]) {  # 4C fit to e+e- -> pi+pi- gamma gamma l+l-
                  nominal                  # Mark as the nominal fit (corrected four-momenta are kept)
                  constrain_four_momentum  # Constrain total four-momentum to the CMS energy
                  chi2_cut 200             # Loose chi2 < 200 (tight cut optimised later in ROOT)
                }

# Attach a representative decay card (the pi+pi-gamma-gamma-l+l- final state is common
# to all four signal modes, so the generated header covers every one of them).
my_algorithm.with_decay_card(decay_card_chic1_ee).apply(event_selection)

# Execute on real data, matching inclusive MC, and all exclusive signal MC samples
root_files = my_algorithm.execute_on(data_points + incMC_points +
                                     exMC_chic1_ee + exMC_chic1_mumu +
                                     exMC_chic2_ee + exMC_chic2_mumu)