# BESIII paper 1012.5131v2 — Study of a_0^0(980)-f_0(980) mixing
#   Channel I : J/psi -> phi f_0(980) -> phi a_0^0(980) -> phi eta pi0            (2.25e8 J/psi)
#   Channel II: psi' -> gamma chi_c1 -> gamma pi0 a_0^0(980) -> gamma pi0 f_0(980) -> gamma pi0 pi+ pi-  (1.06e8 psi')
# "S" in the decay cards denotes the narrow a_0^0(980)-f_0(980) mixing signal
# (m = 991.3 MeV/c^2, Gamma = 8 MeV/c^2) that is generated by the efficiency MC.

### Dataset preparation ###
jpsi_data  = DatasetManager.real_data.find("708_3097")      # J/psi data sample
jpsi_incMC = DatasetManager.inclusive_mc.find("708_3097")   # J/psi inclusive MC (2.0e8 events)
psip_data  = DatasetManager.real_data.find("709_3686")      # psi(2S) data sample
psip_incMC = DatasetManager.inclusive_mc.find("709_3686")   # psi(2S) inclusive MC (1.0e8 events)

# Signal MC for J/psi -> phi S, S -> eta pi0 (mixing signal f_0(980) -> a_0^0(980))
decay_card_fa = <<~DECAYCARD
    Decay J/psi
    1.0000 phi S                    PHSP;
    Enddecay

    Decay phi
    1.0000 K+ K-                    VSS;
    Enddecay

    Decay S
    1.0000 eta pi0                  PHSP;
    Enddecay

    Decay eta
    1.0000 gamma gamma              PHSP;
    Enddecay

    Decay pi0
    1.0000 gamma gamma              PHSP;
    Enddecay

    End
DECAYCARD

# Signal MC for psi' -> gamma chi_c1 -> gamma pi0 S, S -> pi+ pi- (mixing signal a_0^0(980) -> f_0(980))
decay_card_af = <<~DECAYCARD
    Decay psi(2S)
    1.0000 gamma chi_c1             PHSP;
    Enddecay

    Decay chi_c1
    1.0000 pi0 S                    PHSP;
    Enddecay

    Decay S
    1.0000 pi+ pi-                  PHSP;
    Enddecay

    Decay pi0
    1.0000 gamma gamma              PHSP;
    Enddecay

    End
DECAYCARD

exMC_fa = DatasetManager.create_exclusive_mc do |config|
    config.sample_name     = "jpsi_phi_f0_to_a0_eta_pi0"
    config.related_dataset = jpsi_data
    config.events          = 200000
    config.decay_card      = decay_card_fa
    config.cross_section   = :default
end

exMC_af = DatasetManager.create_exclusive_mc do |config|
    config.sample_name     = "psip_gamma_chic1_pi0_f0_to_a0_pi_pi"
    config.related_dataset = psip_data
    config.events          = 200000
    config.decay_card      = decay_card_af
    config.cross_section   = :default
end

### Event selection (BOSS) — Channel I: J/psi -> phi f_0(980) -> phi a_0^0(980) -> phi eta pi0 ###
alg_name_fa = "JpsiPhiEtaPi0Mixing"
alg_fa = Algorithm.new(alg_name_fa)
alg_fa.set_header(["#{alg_name_fa}Alg/#{alg_name_fa}.h"])
      .set_constant({"ECMS" => [:double, 3.097]})

sel_fa = Selection.new
sel_fa.select_track {
         cos_theta 0.93
         Vz        20.0    # tracks within +-20 cm of the IP along the beam direction
         Vr        2.0     # tracks within 2 cm of the IP in the plane perpendicular to the beam
         nChrp     "==1"   # two oppositely charged tracks
         nChrn     "==1"
         nNet      "==0"
       }
       .select_photon {
         tdc_emc_start     0
         tdc_emc_end       14
         angle_to_track    10.0    # shower > 10 deg away from the nearest charged track
         energyThreshold_b 0.025   # barrel : E > 25 MeV (|cos theta| < 0.80)
         energyThreshold_e 0.050   # endcap : E > 50 MeV (0.86 < |cos theta| < 0.92)
         nGam              ">=4"   # enough photons for one eta and one pi0 candidate
       }
       .pid(method: :probability) {
         prob_cut 0.001
         identify :kaon, against: [:pion, :proton]   # both tracks identified as kaons
         nkp "==1"
         nkm "==1"
       }
       # 6C kinematic fit to J/psi -> K+ K- eta pi0
       # (4-momentum of J/psi + m(pi0) + m(eta) constraints).
       # The combination with the smallest chi2_6C is retained automatically.
       .kinematic_fit([:kp, :km, :gamma, :gamma, :gamma, :gamma]) {
         nominal
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:eta)
         constrain_four_momentum
         chi2_cut 200   # loose BOSS cut; the paper requires chi2_6C < 60 (applied in ROOT)
       }
       # Competing hypothesis J/psi -> K+ K- eta eta (chi2 stored for the ROOT-level
       # probability comparison against the signal hypothesis)
       .kinematic_fit([:kp, :km, :gamma, :gamma, :gamma, :gamma]) {
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:eta)
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:eta)
         constrain_four_momentum
       }
       # Competing hypothesis J/psi -> K+ K- pi0 pi0 (chi2 stored for the ROOT-level veto)
       .kinematic_fit([:kp, :km, :gamma, :gamma, :gamma, :gamma]) {
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         constrain_four_momentum
       }

alg_fa.note(:mixing_signal_parameters,
            "Efficiency MC: J/psi -> phi S with S the mixing signal described by a narrow scalar " \
            "Breit-Wigner of mass 991.3 MeV/c^2 (centre of m(K+K-) and m(K0 Kbar0)) and width " \
            "8 MeV/c^2, decaying uniformly to eta pi0.")
      .note(:mass_pair_chi2,
            "The pi0 -> gamma gamma and eta -> gamma gamma candidates are formed from photon pairs " \
            "kinematically fitted to the known resonance masses; the chi^2 of that 1-d.o.f. fit is " \
            "required to be < 25. This pair-level chi^2 is absorbed into the mass constraints of the " \
            "6C fit and is not separately cut in BOSS.")
      .note(:decay_angle_cut,
            "|cos(theta_decay)| < 0.95 required for the photon in the eta/pi0 rest frame " \
            "(polar angle w.r.t. the eta/pi0 direction in the J/psi rest frame) to remove wrong " \
            "photon combinations. Not expressible in the DSL selection blocks; applied in ROOT.")
      .note(:eta_pi0_combination_choice,
            "If more than one eta pi0 combination survives, the one with the smallest chi2_6C is " \
            "retained (smallest-chi2 combination selection of the kinematic fit).")
      .note(:competing_hypothesis_veto,
            "Events are also fitted to J/psi -> K+ K- eta eta and J/psi -> K+ K- pi0 pi0; the fit " \
            "probability of each competing hypothesis must be smaller than the probability of the " \
            "signal hypothesis J/psi -> K+ K- eta pi0. The competing chi2 values are stored by the " \
            "two non-nominal kinematic fits; the probability comparison is applied in ROOT.")
      .note(:phi_window_and_sideband,
            "phi signal region |m(K+K-) - 1.02| < 0.015 GeV/c^2; phi sideband " \
            "1.065 < M(K+K-) < 1.095 GeV/c^2 used for background estimation. Windows applied in ROOT.")
      .note(:background_channels,
            "Backgrounds checked with exclusive MC: J/psi -> phi pi0 pi0 (via f_0(980), f_2(1270) or " \
            "phase space), J/psi -> K* K eta + c.c., J/psi -> K_2*(1430) K eta + c.c., " \
            "J/psi -> gamma f_2(1950) -> gamma K* Kbar*. The eta pi0 mass spectrum of these channels " \
            "is smooth and does not peak in the 980 MeV/c^2 region.")
      .note(:underlying_a0_contribution,
            "The underlying J/psi -> phi a_0^0(980) process (via gamma* or K* K loops) gives a much " \
            "broader (50-100 MeV/c^2) eta pi0 distribution than the mixing signal; its yield is " \
            "extracted from the simultaneous fit to the eta pi0 mass spectrum.")
      .note(:mass_spectrum_fit,
            "Simultaneous unbinned maximum-likelihood fit to the eta pi0 mass spectra recoiling " \
            "against the phi signal region and against the phi sideband. Signal-region PDF = " \
            "mixing signal (MC shape of a narrow Breit-Wigner) + a_0^0(980) (Flatte) + 2nd-order " \
            "polynomial; sideband PDF = 2nd-order polynomial only. Fitted yields: " \
            "N(f_0 -> a_0^0) = 25.8 +- 8.6 (3.4 sigma), N(a_0^0(980)) = 13.6 +- 24.8. Performed at ROOT level.")
      .note(:upper_limit_bayesian,
            "Bayesian 90% C.L. upper limits from the mass fit: 37.5 mixing events and 50.8 " \
            "a_0^0(980) events; the final quoted upper limit on the branching ratio uses " \
            "N_fa^U.L. = 39.7 events and a one-sigma-lowered efficiency.")
      .note(:efficiency,
            "epsilon_fa = (18.5 +- 0.2)% for the mixing signal and epsilon_a = (18.3 +- 0.2)% for " \
            "the underlying J/psi -> phi a_0^0(980) -> phi eta pi0 process.")
      .note(:normalization,
            "N_J/psi = (2.252 +- 0.028) x 10^8; Br(phi -> K+ K-), Br(eta -> gamma gamma) and " \
            "Br(pi0 -> gamma gamma) taken from the PDG.")
      .note(:systematics,
            "Tracking 2%/track, PID 2%/track, photon detection 1%/photon, pi0 2.0% per pi0, " \
            "eta 2.0% per eta, kinematic fit 0.9%, J/psi counting 1.3%, background-shape and " \
            "fit-range variations on the mass fit; parameterization of the mixing line shape " \
            "quoted separately (9.4% for f_0 -> a_0^0).")

alg_fa.with_decay_card(decay_card_fa).apply(sel_fa)
root_files_fa = alg_fa.execute_on([jpsi_data, jpsi_incMC, exMC_fa])

### Event selection (BOSS) — Channel II: psi' -> gamma chi_c1 -> gamma pi0 f_0(980) -> gamma pi0 pi+ pi- ###
alg_name_af = "PsipGammaPi0PiPiMixing"
alg_af = Algorithm.new(alg_name_af)
alg_af.set_header(["#{alg_name_af}Alg/#{alg_name_af}.h"])
      .set_constant({"ECMS" => [:double, 3.686]})

sel_af = Selection.new
sel_af.select_track {
         cos_theta 0.93
         Vz        20.0    # tracks within +-20 cm of the IP along the beam direction
         Vr        2.0     # tracks within 2 cm of the IP in the plane perpendicular to the beam
         nChrp     "==1"   # two oppositely charged tracks
         nChrn     "==1"
         nNet      "==0"
       }
       .select_photon {
         tdc_emc_start     0
         tdc_emc_end       14
         angle_to_track    10.0    # shower > 10 deg away from the nearest charged track
         energyThreshold_b 0.025   # barrel : E > 25 MeV (|cos theta| < 0.80)
         energyThreshold_e 0.050   # endcap : E > 50 MeV (0.86 < |cos theta| < 0.92)
         nGam              ">=3"   # at least three photons (one pi0 plus the radiative photon)
       }
       .pid(method: :probability) {
         prob_cut 0.001
         identify :pion, against: [:kaon, :proton]   # both tracks identified as pions
         npip "==1"
         npim "==1"
       }
       # 5C kinematic fit to psi' -> gamma pi0 pi+ pi-
       # (4-momentum of psi' + m(pi0) constraint).
       # The combination with the smallest chi2_5C is retained automatically.
       .kinematic_fit([:gamma, :gamma, :gamma, :pip, :pim]) {
         nominal
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         constrain_four_momentum
         chi2_cut 200   # loose BOSS cut; the paper requires chi2_5C < 60 (applied in ROOT)
       }
       # Competing hypothesis psi' -> pi0 pi+ pi- (no radiative photon; chi2 stored)
       .kinematic_fit([:gamma, :gamma, :pip, :pim]) {
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         constrain_four_momentum
       }
       # Competing hypothesis psi' -> pi0 pi0 pi+ pi- (chi2 stored)
       .kinematic_fit([:gamma, :gamma, :gamma, :gamma, :pip, :pim]) {
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         invariant_mass_of(:gamma, :gamma).constrain_to_nominal_mass_of(:pi0)
         constrain_four_momentum
       }

alg_af.note(:mixing_signal_parameters,
            "Efficiency MC: psi' -> gamma chi_c1 -> gamma pi0 S with S the mixing signal described " \
            "by a narrow scalar Breit-Wigner of mass 991.3 MeV/c^2 and width 8 MeV/c^2, decaying " \
            "isotropically to pi+ pi-.")
      .note(:mass_pair_chi2,
            "The pi0 -> gamma gamma candidate is formed from a photon pair kinematically fitted to " \
            "the nominal pi0 mass with the 1-d.o.f. chi^2 required to be < 25; this requirement is " \
            "carried by the pi0 mass constraint of the 5C fit and is not cut separately in BOSS.")
      .note(:decay_angle_cut,
            "|cos(theta_decay)| < 0.95 required for the photon in the pi0 rest frame " \
            "(polar angle w.r.t. the pi0 direction in the psi' rest frame) to remove wrong photon " \
            "combinations. Not expressible in the DSL selection blocks; applied in ROOT.")
      .note(:competing_hypothesis_veto,
            "Events are also fitted to psi' -> pi0 pi+ pi- and psi' -> pi0 pi0 pi+ pi-; the fit " \
            "probability of each competing hypothesis must be smaller than the probability of the " \
            "signal hypothesis psi' -> gamma pi0 pi+ pi-. The competing chi2 values are stored by " \
            "the two non-nominal kinematic fits; the probability comparison is applied in ROOT.")
      .note(:two_track_angle,
            "Angle between the two charged tracks required to be < 160 deg to reject backgrounds " \
            "containing a J/psi decaying to leptons. Not expressible in the DSL selection blocks; " \
            "applied in ROOT.")
      .note(:emc_energy_over_momentum,
            "E/p < 0.85 for each charged track (EMC deposited energy over MDC momentum), used to " \
            "reject J/psi -> lepton backgrounds. Not expressible in the DSL selection blocks; " \
            "can be applied with a ROOT-level cut or a for_each filter.")
      .note(:gamma_gamma_jpsi_veto,
            "Backgrounds with gamma gamma J/psi final states rejected by requiring the mass " \
            "recoiling from any photon pair to lie outside the J/psi window: " \
            "|M_recoil(gamma gamma) - 3.097 GeV/c^2| > 0.06 GeV/c^2. Applied in ROOT.")
      .note(:chic1_window_and_sideband,
            "chi_c1 mass window 3.49 < M(pi0 pi+ pi-) < 3.54 GeV/c^2; chi_c1 sideband " \
            "3.39-3.45 GeV/c^2 and 3.54-3.59 GeV/c^2 used for background estimation. Applied in ROOT.")
      .note(:background_channels,
            "Backgrounds checked with exclusive MC: psi' -> gamma chi_c1, chi_c1 -> gamma gamma J/psi " \
            "-> gamma gamma pi+ pi- pi0; psi' -> pi+ pi- pi0; psi' -> gamma chi_c1 -> gamma a_0^+- pi^-+ " \
            "-> gamma eta pi+ pi- pi0; psi' -> eta pi+ pi0. No peak near 980 MeV/c^2 is produced.")
      .note(:underlying_f0_contribution,
            "The f_0(980) from other psi' -> gamma chi_c1 -> gamma pi0 f_0(980) processes is much " \
            "broader than the a_0^0(980) -> f_0(980) mixing signal; represented by a Flatte formula " \
            "in the simultaneous fit to the pi+ pi- mass spectrum.")
      .note(:mass_spectrum_fit,
            "Simultaneous unbinned maximum-likelihood fit to the pi+ pi- mass spectra in the chi_c1 " \
            "signal window and in the chi_c1 sideband. Signal-region PDF = mixing signal (MC shape) " \
            "+ f_0(980) from other processes (Flatte) + 2nd-order polynomial; sideband PDF = " \
            "2nd-order polynomial only. Fitted yields: N(a_0^0 -> f_0) = 6.4 +- 3.2 (1.9 sigma), " \
            "N(f_0(980)) = 0.0 +- 8.6. Performed at ROOT level.")
      .note(:upper_limit_bayesian,
            "Bayesian 90% C.L. upper limits from the mass fit: 11.9 mixing events; the final quoted " \
            "upper limit on the branching ratio uses N_af^U.L. = 13.0 events and a one-sigma-lowered " \
            "efficiency.")
      .note(:efficiency,
            "epsilon_af = (22.3 +- 0.2)% for the mixing signal and epsilon_f = (20.5 +- 0.2)% for " \
            "the underlying psi' -> gamma pi0 f_0(980) -> gamma pi0 pi+ pi- process.")
      .note(:normalization,
            "N_psi' = (1.06 +- 0.04) x 10^8; Br(pi0 -> gamma gamma) taken from the PDG.")
      .note(:systematics,
            "Tracking 2%/track, PID 2%/track, photon detection 1%/photon, pi0 2.0% per pi0, " \
            "kinematic fit 1.7%, psi' counting 4.0%, background-shape and fit-range variations on " \
            "the mass fit; parameterization of the mixing line shape quoted separately " \
            "(43.8% for a_0^0 -> f_0).")

alg_af.with_decay_card(decay_card_af).apply(sel_af)
root_files_af = alg_af.execute_on([psip_data, psip_incMC, exMC_af])
