# BESIII paper 1207.5646v4 — chi_cJ -> Lambda anti-Lambda pi+ pi-
# via psi(2S) -> gamma chi_cJ. Uses 106 M psi(2S) events.

### Dataset description ###
psip_data   = DatasetManager.real_data.find("709_3686")
psip_incMC  = DatasetManager.inclusive_mc.find("709_3686")

# Decay card: psi(2S) -> gamma chi_cJ, chi_cJ -> Lambda anti-Lambda pi+ pi-
# (non-resonant + intermediate Sigma(1385) contributions share the same final state).
# One decay card is generated for each of chi_c0/c1/c2; here we take chi_c1 as example
# and rely on set_constant + selection to be reused.
decay_card_chic1 = <<~DECAYCARD
    Decay psi(2S)
    1.0000  gamma chi_c1                HELAMP 1.0 0.0 1.0 0.0;
    Enddecay

    Decay chi_c1
    1.0000  Lambda0 anti-Lambda0 pi+ pi-   PHSP;
    Enddecay

    Decay Lambda0
    1.0000  p+ pi-                       HypWK;
    Enddecay

    Decay anti-Lambda0
    1.0000  anti-p- pi+                  HypWK;
    Enddecay

    End
DECAYCARD

exMC_chic1 = DatasetManager.create_exclusive_mc do |config|
  config.sample_name    = "psip_gamma_chic1_Lambda_Lambdabar_pipi"
  config.related_dataset = psip_data
  config.events         = 500_000
  config.decay_card     = decay_card_chic1
  config.cross_section  = :default
end
exMC_chic1.save_to_config(format: :yaml, file_path: 'temp_for_test')

### Event selection (BOSS) ###
alg_name  = "ChiCJLLpipi"
alg       = Algorithm.new(alg_name)
alg.set_header(["#{alg_name}Alg/#{alg_name}.h"])
   .set_constant({"ECMS" => [:double, 3.686]})
   .set_alias({"std::vector<double>" => "Vdouble"})

event_selection = Selection.new
event_selection.select_track {
                  cos_theta   0.93        # |cos theta| < 0.93
                  Vz         10.0         # |Vz| < 10 cm (for tracks NOT from Lambda; loose default)
                  Vr          1.0         # |Vr| < 1 cm
                  nChrp     ">=2"         # >=2 positive tracks (p, pi+)
                  nChrn     ">=2"         # >=2 negative tracks (pbar, pi-)
                  nNet      "==0"         # net charge zero
                }
               .select_photon {
                  energyThreshold_b 0.025 # barrel 25 MeV
                  energyThreshold_e 0.050 # endcap 50 MeV
                  nGam    ">=1"           # at least one E1 photon
                }
               # PID not used per selection (1). Treat all pos tracks as pip or proton;
               # secondary_vertex_fit picks the p pi- combination best matching Lambda mass.
               .assign({:chrgp => :prp, :chrgp => :pip, :chrgn => :prm, :chrgn => :pim})
               .secondary_vertex_fit([:prp, :pim]) {
                  build_virtual_particle(:Lambda).by_minimizing_mass_difference
                  remove_used_particle_from_candidate_list
               }
               .secondary_vertex_fit([:prm, :pip]) {
                  build_virtual_particle(:Lambda_bar).by_minimizing_mass_difference
                  remove_used_particle_from_candidate_list
               }
               # 4C kinematic fit: gamma Lambda Lambdabar pi+ pi- constrained to sqrt(s)
               .kinematic_fit([:gamma, :Lambda, :Lambda_bar, :pip, :pim]) {
                  nominal
                  constrain_four_momentum
                  chi2_cut 200            # loose BOSS cut; paper uses chi2 < 80, applied in ROOT
               }

alg.note(:jpsi_veto,
         "Background from psi' -> pi+pi- J/psi with J/psi -> gamma Lambda Lambdabar is vetoed by " \
         "requiring pi+pi- recoil mass > 3.108 GeV/c^2 OR < 3.088 GeV/c^2. Applied in ROOT.")
   .note(:sigma0_veto,
         "Background from psi' -> Sigma(1385) Sigma(1385), Sigma(1385) -> Sigma0 pi, Sigma0 -> gamma Lambda " \
         "vetoed by discarding events with M(gamma Lambda) or M(gamma anti-Lambda) in [1.183, 1.202] GeV/c^2. Applied in ROOT.")
   .note(:xi_veto,
         "Xi+/- background rejected by requiring M(Lambda pi-) and M(anti-Lambda pi+) < 1.312 GeV/c^2 " \
         "or > 1.331 GeV/c^2. Applied in ROOT.")
   .note(:multiple_modes,
         "Same final state (gamma Lambda Lambdabar pi+ pi-) is analyzed for chi_c0, chi_c1, chi_c2. " \
         "Selection is identical; only decay card mother differs. Additional decay cards for chi_c0 and chi_c2 " \
         "can be generated by cloning decay_card_chic1 and changing the chi_c1 mother to chi_c0/chi_c2.")

alg.with_decay_card(decay_card_chic1).apply(event_selection)
root_files = alg.execute_on([psip_data, psip_incMC, exMC_chic1])
