# ============================================================================
# arXiv:1505.02559v1 (BESIII)
# An Improved Limit for Gamma_ee of X(3872) and Gamma_ee Measurement of psi(3686)
#
# ISR (untagged) search for e+e- -> gamma_ISR X(3872) -> gamma_ISR pi+ pi- J/psi,
# with J/psi -> l+ l- (l = e, mu). The same final state contains a large
# e+e- -> gamma_ISR psi(3686) -> gamma_ISR pi+ pi- J/psi component, which is used
# to measure Gamma_ee[psi(3686)] as a benchmark.
#
# Data: 2.94 fb^-1 at sqrt(s) = 4.009, 4.230, 4.260 and 4.360 GeV.
# The ISR photon is emitted at small polar angles (|cos(theta_ISR)| > 0.95),
# is not detected, and is reconstructed from the missing momentum of the event
# (untagged ISR method).
#
# BOSS part only: decay cards, exclusive MC, event selection up to the 2C
# kinematic fit.
# ============================================================================

### Dataset description ###
# Real data at the four centre-of-mass energies used in the analysis
data_4009 = DatasetManager.real_data.find("703_4009")   # 482 pb^-1
data_4230 = DatasetManager.real_data.find("703_4230")   # 1092 pb^-1
data_4260 = DatasetManager.real_data.find("703_4260")   # 826 pb^-1
data_4360 = DatasetManager.real_data.find("703_4360")   # 540 pb^-1

# Corresponding inclusive MC samples
incMC_4009 = DatasetManager.inclusive_mc.find("703_4009")
incMC_4230 = DatasetManager.inclusive_mc.find("703_4230")
incMC_4260 = DatasetManager.inclusive_mc.find("703_4260")
incMC_4360 = DatasetManager.inclusive_mc.find("703_4360")

data_points = [data_4009, data_4230, data_4260, data_4360]
incMCs      = [incMC_4009, incMC_4230, incMC_4260, incMC_4360]

# ----------------------------------------------------------------------------
# Signal decay cards: e+e- -> gamma_ISR X(3872) and e+e- -> gamma_ISR psi(3686),
# both followed by -> pi+ pi- J/psi with J/psi -> l+ l-.
# ISR is generated by the KKMC / vectorISR machinery; the In the card the ISR
# photon is kept as an explicit daughter of the psi(4260) so that the exclusive
# final state gamma pi+ pi- l+ l- is complete.
# ----------------------------------------------------------------------------
# X(3872) signal, J/psi -> e+ e-
decay_card_X3872_ee = <<~DECAYCARD
    Decay psi(4260)
    1.0000 gamma X(3872) PHSP;
    Enddecay

    Decay X(3872)
    1.0000 pi+ pi- J/psi PHSP;
    Enddecay

    Decay J/psi
    1.0000 e+ e- PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# X(3872) signal, J/psi -> mu+ mu-
decay_card_X3872_mumu = <<~DECAYCARD
    Decay psi(4260)
    1.0000 gamma X(3872) PHSP;
    Enddecay

    Decay X(3872)
    1.0000 pi+ pi- J/psi PHSP;
    Enddecay

    Decay J/psi
    1.0000 mu+ mu- PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# psi(3686) reference signal, J/psi -> e+ e-
decay_card_psi3686_ee = <<~DECAYCARD
    Decay psi(4260)
    1.0000 gamma psi(3686) PHSP;
    Enddecay

    Decay psi(3686)
    1.0000 pi+ pi- J/psi PHSP;
    Enddecay

    Decay J/psi
    1.0000 e+ e- PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# psi(3686) reference signal, J/psi -> mu+ mu-
decay_card_psi3686_mumu = <<~DECAYCARD
    Decay psi(4260)
    1.0000 gamma psi(3686) PHSP;
    Enddecay

    Decay psi(3686)
    1.0000 pi+ pi- J/psi PHSP;
    Enddecay

    Decay J/psi
    1.0000 mu+ mu- PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# ----------------------------------------------------------------------------
# Background decay cards simulated for the background study
# ----------------------------------------------------------------------------
# e+e- -> eta J/psi (dominant background), eta -> pi+ pi- pi0
decay_card_bg_etaJpsi = <<~DECAYCARD
    Decay psi(4260)
    1.0000 eta J/psi PHSP;
    Enddecay

    Decay eta
    1.0000 pi+ pi- pi0 PHSP;
    Enddecay

    Decay pi0
    1.0000 gamma gamma PHSP;
    Enddecay

    Decay J/psi
    1.0000 e+ e- PHOTOS VLL;
    Enddecay

    End
DECAYCARD

# e+e- -> gamma_ISR pi+ pi- pi+ pi-
decay_card_bg_4pi = <<~DECAYCARD
    Decay psi(4260)
    1.0000 gamma pi+ pi- pi+ pi- PHSP;
    Enddecay

    End
DECAYCARD

# ----------------------------------------------------------------------------
# Exclusive MC: signal and reference samples at each centre-of-mass energy
# ----------------------------------------------------------------------------
exMC_X3872_ee = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "ISR_X3872_ee"      # auto-suffixed with the dataset key
  config.events        = 100_000
  config.decay_card    = decay_card_X3872_ee
  config.cross_section = :default
end

exMC_X3872_mumu = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "ISR_X3872_mumu"
  config.events        = 100_000
  config.decay_card    = decay_card_X3872_mumu
  config.cross_section = :default
end

exMC_psi3686_ee = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "ISR_psi3686_ee"
  config.events        = 100_000
  config.decay_card    = decay_card_psi3686_ee
  config.cross_section = :default
end

exMC_psi3686_mumu = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "ISR_psi3686_mumu"
  config.events        = 100_000
  config.decay_card    = decay_card_psi3686_mumu
  config.cross_section = :default
end

exMC_bg_etaJpsi = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "bg_etaJpsi"
  config.events        = 100_000
  config.decay_card    = decay_card_bg_etaJpsi
  config.cross_section = :default
end

exMC_bg_4pi = DatasetManager.create_exclusive_mc_for(data_points) do |config|
  config.sample_name   = "bg_4pi_ISR"
  config.events        = 100_000
  config.decay_card    = decay_card_bg_4pi
  config.cross_section = :default
end

### Event selection (BOSS) ###
# --- J/psi -> e+ e- channel -------------------------------------------------
alg_name_ee = "ISRX3872EE"
alg_ee = Algorithm.new(alg_name_ee)
alg_ee.set_header(["#{alg_name_ee}Alg/#{alg_name_ee}.h"])
      .set_alias({"std::vector<double>" => "Vdouble"})
      # Multi-energy scan: ECMS is injected per dataset at run time, so no
      # ECMS constant is declared here.

# --- J/psi -> mu+ mu- channel -----------------------------------------------
alg_name_mumu = "ISRX3872MuMu"
alg_mumu = Algorithm.new(alg_name_mumu)
alg_mumu.set_header(["#{alg_name_mumu}Alg/#{alg_name_mumu}.h"])
        .set_alias({"std::vector<double>" => "Vdouble"})

# Common selection: four charged tracks with net charge zero, lepton/pion
# separation by momentum (p > 1 GeV/c -> lepton, p < 600 MeV/c -> pion), then
# the 2C kinematic fit for the untagged gamma_ISR pi+ pi- l+ l- final state.
event_selection = Selection.new
event_selection.select_track {
                  cos_theta   0.93   # |cos(theta)| < 0.93 in the MDC
                  Vz          10.0   # |Vz| < 10 cm along the beam direction
                  Vr          1.0    # Vr < 1 cm in the plane perpendicular to the beam
                  nChrp       "==2"  # exactly two positively charged tracks
                  nChrn       "==2"  # exactly two negatively charged tracks
                  nNet        "==0"  # net charge zero
                }
               .pid(method: :probability) {
                  prob_cut 0.001
                  # The J/psi carries most of the total momentum, so leptons are
                  # the high-momentum tracks (p > 1 GeV/c in the lab frame)
                  identify_high_momentum_leptons treat_as_lepton_if_momentum_above: 1.0,
                                                 treat_as_electron_if_energy_above: 0.4
                  identify :pion, against: [:kaon, :proton]  # the two pions
                  nlp  "==1"
                  nlm  "==1"
                  npip "==1"
                  npim "==1"
                }
               # Pion candidates must have lab momentum below 600 MeV/c
               .for_each(:pip) { where { p > 0.6 }; remove }
               .for_each(:pim) { where { p > 0.6 }; remove }
               # 2C kinematic fit of the untagged final state gamma_ISR pi+ pi- l+ l-:
               # the ISR photon is missing (inferred from the missing momentum) and
               # constrained to a zero mass, and the lepton pair is constrained to
               # the nominal J/psi mass
               .kinematic_fit([:pip, :pim, :lp, :lm]) {
                  nominal
                  miss_track_of :gamma                                          # undetected ISR photon, mass constrained to zero
                  invariant_mass_of(:lp, :lm).constrain_to_nominal_mass_of(:jpsi)  # J/psi mass constraint
                  chi2_cut 200   # loose BOSS-pass cut; the paper's chi2_2C < 15 is applied in ROOT
                }

# Dedicated selection objects for the two lepton channels
selection_ee   = event_selection.dup
selection_mumu = event_selection.dup

# Notes for BOSS-side criteria that have no dedicated DSL construct
alg_ee
  .note(:chi2_selection, "The published selection uses a two-constraint (2C) " \
        "kinematic fit under the hypothesis gamma_ISR pi+ pi- l+ l- with " \
        "chi2_2C < 15; the two constraints are the J/psi mass of the lepton pair " \
        "and the zero mass of the missing ISR photon. The nominal BOSS pass uses " \
        "the loose default chi2_cut 200 and the tight value is applied at the ROOT " \
        "stage. A relative efficiency correction of 2% (and an uncertainty of " \
        "0.4% on the luminosity-weighted average) accounts for the data-MC " \
        "difference in the chi2_2C distribution.")
  .note(:background_veto, "The ISR photon is required to be emitted at small " \
        "polar angles, |cos(theta_ISR)| > 0.95, i.e. almost collinear with the " \
        "beam direction. The photon is not detected in this region and its energy " \
        "and polar angle are computed from the missing momentum of the event " \
        "(untagged ISR method). This suppresses the irreducible " \
        "e+e- -> gamma X(3872) background from Y(4260) -> gamma X(3872), whose " \
        "photon is predominantly emitted at large polar angles; the cut is " \
        "applied on missing-momentum quantities in the ROOT stage.")
  .note(:background_veto, "The J/psi candidate is selected with " \
        "3.05 <= M(l+ l-) <= 3.14 GeV/c^2 (resolution 16 MeV/c^2). The opening " \
        "angle of the two pion tracks is required to satisfy cos(alpha_pipi) <= 0.6, " \
        "which removes the e+e- -> eta J/psi background and mis-identified " \
        "electrons from photon conversion (the eta decay products are strongly " \
        "boosted and hence collimated in the lab frame).")
  .note(:pid_correction_method, "Leptons are identified by their lab momentum " \
        "(p > 1 GeV/c) and pions by p < 600 MeV/c, and electrons are separated " \
        "from muons with the ratio of the EMC energy deposit to the MDC momentum, " \
        "E/p > 0.4 for electrons and E/p <= 0.4 for muons; MC studies show the " \
        "J/psi -> e+ e- background to be negligible. The E/p criterion is not " \
        "expressible in the DSL lepton-identification block, which instead uses " \
        "the EMC energy threshold treat_as_electron_if_energy_above.")
  .note(:efficiency_curve, "The ISR X(3872) detection efficiency is obtained from " \
        "a MC simulation using the vectorISR model, while the ISR psi(3686) " \
        "efficiency uses the PHOKHARA generator (0.5% precision); the " \
        "luminosity-weighted average difference between the two generators, 3.4%, " \
        "is taken as the systematic uncertainty of the vectorISR model. The " \
        "integrals I_A of the radiator function over the signal region carry a " \
        "0.7% uncertainty. FSR effects are negligible since events with a hard " \
        "FSR photon are rejected by the J/psi mass constraint of the kinematic fit.")

alg_mumu
  .note(:chi2_selection, "The published selection uses a two-constraint (2C) " \
        "kinematic fit under the hypothesis gamma_ISR pi+ pi- l+ l- with " \
        "chi2_2C < 15; the two constraints are the J/psi mass of the lepton pair " \
        "and the zero mass of the missing ISR photon. The nominal BOSS pass uses " \
        "the loose default chi2_cut 200 and the tight value is applied at the ROOT " \
        "stage. A relative efficiency correction of 2% (and an uncertainty of " \
        "0.4% on the luminosity-weighted average) accounts for the data-MC " \
        "difference in the chi2_2C distribution.")
  .note(:background_veto, "The ISR photon is required to be emitted at small " \
        "polar angles, |cos(theta_ISR)| > 0.95, i.e. almost collinear with the " \
        "beam direction. The photon is not detected in this region and its energy " \
        "and polar angle are computed from the missing momentum of the event " \
        "(untagged ISR method). This suppresses the irreducible " \
        "e+e- -> gamma X(3872) background from Y(4260) -> gamma X(3872), whose " \
        "photon is predominantly emitted at large polar angles; the cut is " \
        "applied on missing-momentum quantities in the ROOT stage.")
  .note(:background_veto, "The J/psi candidate is selected with " \
        "3.05 <= M(l+ l-) <= 3.14 GeV/c^2 (resolution 16 MeV/c^2). The opening " \
        "angle of the two pion tracks is required to satisfy cos(alpha_pipi) <= 0.6, " \
        "which removes the e+e- -> eta J/psi background and mis-identified " \
        "electrons from photon conversion (the eta decay products are strongly " \
        "boosted and hence collimated in the lab frame).")
  .note(:pid_correction_method, "Leptons are identified by their lab momentum " \
        "(p > 1 GeV/c) and pions by p < 600 MeV/c, and electrons are separated " \
        "from muons with the ratio of the EMC energy deposit to the MDC momentum, " \
        "E/p > 0.4 for electrons and E/p <= 0.4 for muons; MC studies show the " \
        "J/psi -> e+ e- background to be negligible. The E/p criterion is not " \
        "expressible in the DSL lepton-identification block, which instead uses " \
        "the EMC energy threshold treat_as_electron_if_energy_above.")
  .note(:efficiency_curve, "The ISR X(3872) detection efficiency is obtained from " \
        "a MC simulation using the vectorISR model, while the ISR psi(3686) " \
        "efficiency uses the PHOKHARA generator (0.5% precision); the " \
        "luminosity-weighted average difference between the two generators, 3.4%, " \
        "is taken as the systematic uncertainty of the vectorISR model. The " \
        "integrals I_A of the radiator function over the signal region carry a " \
        "0.7% uncertainty. FSR effects are negligible since events with a hard " \
        "FSR photon are rejected by the J/psi mass constraint of the kinematic fit.")

# Generate the BOSS algorithm packages (the pi+ pi- J/psi mass spectrum is fitted
# in ROOT to extract the psi(3686) and X(3872) yields)
alg_ee.with_decay_card(decay_card_X3872_ee).apply(selection_ee)
alg_mumu.with_decay_card(decay_card_X3872_mumu).apply(selection_mumu)

# Execute on real data, inclusive MC, signal/reference MC and background MC
root_files_ee = alg_ee.execute_on(data_points + incMCs +
                                 exMC_X3872_ee + exMC_psi3686_ee +
                                 exMC_bg_etaJpsi + exMC_bg_4pi)
root_files_mumu = alg_mumu.execute_on(data_points + incMCs +
                                     exMC_X3872_mumu + exMC_psi3686_mumu +
                                     exMC_bg_etaJpsi + exMC_bg_4pi)
