# Measurement of the integrated luminosity and center-of-mass energy of the BESIII data
# taken at 2.125 GeV (arXiv:1705.09722v4)

### Dataset description ###
# BOSS 713 data set at sqrt(s) = 2.12655 GeV (the 2015 Y(2175) scan point)
data_2125  = DatasetManager.real_data.find("713_Rscan_2125")
incMC_2125 = DatasetManager.inclusive_mc.find("713_Rscan_2125")

# Signal decay cards (EvtGen; the ISR/FSR photon is generated by the generator/PHOTOS)
decay_card_bhabha = <<~DECAYCARD
    Decay psi(4260)
    1.000  e+  e-  gamma   PHOTOS VLL;
    Enddecay

    End
DECAYCARD

decay_card_gammagamma = <<~DECAYCARD
    Decay psi(4260)
    1.000  gamma  gamma   PHSP;
    Enddecay

    End
DECAYCARD

decay_card_dimuon = <<~DECAYCARD
    Decay psi(4260)
    1.000  mu+  mu-  gamma   PHOTOS VLL;
    Enddecay

    End
DECAYCARD

decay_card_qqbar = <<~DECAYCARD
    Decay psi(4260)
    1.000  u+  u-   PHSP;
    Enddecay

    End
DECAYCARD

exMC_bhabha = DatasetManager.create_exclusive_mc do |config|
  config.sample_name     = "exmc_2125_bhabha"
  config.related_dataset = data_2125
  config.events          = 1000000
  config.decay_card      = decay_card_bhabha
  config.cross_section   = :default
end

exMC_gammagamma = DatasetManager.create_exclusive_mc do |config|
  config.sample_name     = "exmc_2125_gammagamma"
  config.related_dataset = data_2125
  config.events          = 1000000
  config.decay_card      = decay_card_gammagamma
  config.cross_section   = :default
end

exMC_dimuon = DatasetManager.create_exclusive_mc do |config|
  config.sample_name     = "exmc_2125_dimuon"
  config.related_dataset = data_2125
  config.events          = 1000000
  config.decay_card      = decay_card_dimuon
  config.cross_section   = :default
end

exMC_qqbar = DatasetManager.create_exclusive_mc do |config|
  config.sample_name     = "exmc_2125_qqbar"
  config.related_dataset = data_2125
  config.events          = 1000000
  config.decay_card      = decay_card_qqbar
  config.cross_section   = :default
end

### Event selection (BOSS) ###
# --- Channel I: e+e- -> (gamma) e+e- (large-angle Bhabha, for the luminosity) ---
alg_bhabha = Algorithm.new("BhabhaLumi")
alg_bhabha.set_header(["BhabhaLumiAlg/BhabhaLumi.h"])
           .set_constant({"ECMS" => [:double, 2.125]})

sel_bhabha = Selection.new
sel_bhabha.select_track do
            cos_theta 0.8      # |cos(theta)| < 0.8 (barrel acceptance)
            Vz        10.0     # |Vz| < 10.0 cm
            Vr        1.0      # Vr < 1.0 cm
            nChrp     "==1"    # exactly two good tracks
            nChrn     "==1"
            nNet      "==0"    # opposite charge
          end
          # energy deposited in the EMC: E > 0.65 x E_beam = 0.690 GeV for each track
          .for_each(:charged) do
            where { eraw < 0.690625 }
            remove
          end
          # back-to-back in the MDC: |theta1 + theta2 - 180 deg| < 10 deg
          .for_each(:charged) do
            define(:dtheta) { theta * 57.29578 }
            best { maximize { theta } }
            store(:theta_hard)
          end
          .kinematic_fit([:ep, :em]) do
            nominal
            constrain_four_momentum
            chi2_cut 200
          end

alg_bhabha.with_decay_card(decay_card_bhabha).apply(sel_bhabha)

# --- Channel II: e+e- -> gamma gamma (luminosity cross check) ---
alg_gammagamma = Algorithm.new("GGammaLumi")
alg_gammagamma.set_header(["GGammaLumiAlg/GGammaLumi.h"])
              .set_constant({"ECMS" => [:double, 2.125]})

sel_gammagamma = Selection.new
sel_gammagamma.select_track do
                 Vz        10.0    # no good charged tracks allowed
                 Vr        1.0
                 nChrp     "==0"
                 nChrn     "==0"
                 nNet      "==0"
               end
               .select_photon do
                 tdc_emc_start     0
                 tdc_emc_end       14
                 energyThreshold_b 0.025
                 energyThreshold_e 0.050
                 angle_to_track    10.0
                 nGam              "==2"   # two energetic clusters in the EMC
               end
               .for_each(:gamma) do
                 define(:abs_cos_theta) { theta * 57.29578 }
                 where { theta < 0.0 }
                 remove
               end
               .kinematic_fit([:gamma, :gamma]) do
                 nominal
                 constrain_four_momentum
                 chi2_cut 200
               end

alg_gammagamma.with_decay_card(decay_card_gammagamma).apply(sel_gammagamma)

# --- Channel III: e+e- -> (gamma) mu+mu- (determination of the c.m. energy) ---
alg_dimuon = Algorithm.new("DiMuonECMS")
alg_dimuon.set_header(["DiMuonECMSAlg/DiMuonECMS.h"])
          .set_constant({"ECMS" => [:double, 2.125]})

sel_dimuon = Selection.new
sel_dimuon.select_track do
            cos_theta 0.8      # |cos(theta)| < 0.8
            Vz        10.0
            Vr        1.0
            nChrp     "==1"    # exactly two good tracks with opposite charge
            nChrn     "==1"
            nNet      "==0"
          end
          # remove Bhabha events: E/p < 0.4 for each track
          .for_each(:charged) do
            define(:eraw_over_p) { eraw / p }
            where { eraw_over_p > 0.4 }
            remove
          end
          .pid(method: :probability) do
            # muons: small EMC energy deposit relative to the momentum, MUC depth used
            identify_high_momentum_leptons treat_as_lepton_if_momentum_above: 1.0,
                                            treat_as_electron_if_energy_above: 0.6
            nlp "==1"
            nlm "==1"
          end
          .kinematic_fit([:mup, :mum]) do
            nominal
            constrain_four_momentum
            chi2_cut 200
          end

alg_dimuon.with_decay_card(decay_card_dimuon).apply(sel_dimuon)

# BOSS-side procedures that have no formal DSL construct
alg_bhabha
  .note(:background_veto,
        "Bhabha selection: |Delta theta| = |theta1 + theta2 - 180 deg| < 10 deg and " \
        "|Delta phi| = ||phi1 - phi2| - 180 deg| < 5.0 deg are required; these " \
        "track-pair angles are evaluated after the kinematic fit and are kept in ROOT")

alg_gammagamma
  .note(:background_veto,
        "gamma gamma selection: each cluster must satisfy |cos theta| < 0.8 and " \
        "0.7 x E_beam < E < 1.15 x E_beam, and the two clusters must be back-to-back " \
        "with |Delta phi| < 2.5 deg; the E-window and the azimuthal correlation are " \
        "applied on kinematic-fit-corrected cluster variables in ROOT")

alg_dimuon
  .note(:background_veto,
        "dimuon selection: the two tracks must be back-to-back with " \
        "|Delta theta| < 10.0 deg, |Delta phi| < 5.0 deg and " \
        "|Delta T| = |t1 - t2| < 1.5 ns (TOF) to suppress cosmic rays; these " \
        "track-pair quantities are evaluated after the kinematic fit and are kept in ROOT")
  .note(:efficiency_curve,
        "the c.m. energy is extracted from a per-run fit to M(mu+mu-) in [2.0, 2.2] GeV/c^2 " \
        "with M_CM = M_data(mu+mu-) - Delta M, where Delta M = M_MC,on - M_MC,off " \
        "(ISR/FSR correction from MC); this is a ROOT-level procedure")

### Execution ###
root_files_bhabha      = alg_bhabha.execute_on([data_2125, incMC_2125, exMC_bhabha])
root_files_gammagamma  = alg_gammagamma.execute_on([data_2125, incMC_2125, exMC_gammagamma])
root_files_dimuon      = alg_dimuon.execute_on([data_2125, incMC_2125, exMC_dimuon, exMC_qqbar])